(() => {
  if (window.__auraAuthLoaded) return; window.__auraAuthLoaded=true;
  const client=window.auraSupabase;
  const login=document.getElementById('login');
  const dashboard=document.getElementById('dashboard');
  if(!login)return;
  login.style.display='grid';
  if(dashboard)dashboard.classList.remove('show');
  const card=login.querySelector('.login');
  const old=card.querySelector('.google');
  if(old)old.remove();
  const conexaoDisponivel=!!client;
  const box=document.createElement('div');box.className='auth-real-box';box.innerHTML=`<button class="auth-provider auth-google" id="authGoogle">🔵 Continuar com Google</button><button class="auth-provider auth-facebook" id="authFacebook">🔵 Continuar com Facebook</button><div class="auth-divider"><span>ou entre com e-mail</span></div><form id="authEmailForm"><input id="authEmail" type="email" autocomplete="email" placeholder="Seu e-mail" required><input id="authPassword" type="password" autocomplete="current-password" placeholder="Sua senha" minlength="6" required><button class="auth-submit" type="submit">Entrar com e-mail</button></form><div class="auth-links"><button type="button" id="authCreate">Criar conta</button><button type="button" id="authForgot">Esqueci minha senha</button></div><p class="auth-message" id="authMessage" role="status"></p>`;card.appendChild(box);
  const css=document.createElement('style');css.textContent=`.auth-real-box{display:grid;gap:10px;margin-top:18px}.auth-provider,.auth-submit{width:100%;padding:14px;border-radius:12px;font:700 12px Arial;cursor:pointer;transition:.2s}.auth-provider:hover,.auth-submit:hover{transform:translateY(-2px);filter:brightness(1.08)}.auth-google{border:1px solid #ffffff2b;background:#fff;color:#15151d}.auth-facebook{border:1px solid #4d8cff88;background:#2468d822;color:#dce9ff}.auth-submit{border:0;background:linear-gradient(110deg,#9364ff,#39aee9);color:#fff}.auth-real-box input{width:100%;padding:13px;border:1px solid #ffffff1c;border-radius:10px;outline:0;background:#080a13;color:#fff;font:12px Arial}.auth-real-box input:focus{border-color:#a273ff}.auth-divider{display:flex;align-items:center;gap:9px;margin:5px 0;color:#777c90;font-size:10px}.auth-divider:before,.auth-divider:after{content:"";height:1px;flex:1;background:#ffffff15}.auth-links{display:flex;justify-content:space-between;gap:8px}.auth-links button{border:0;background:none;color:#bda7ff;font-size:10px;cursor:pointer}.auth-message{display:none;margin:2px 0 0;padding:10px;border-radius:9px;color:#bdeed6;background:#55e6a512;font-size:10px;line-height:1.4}.auth-message.show{display:block}.auth-message.error{color:#ffb7bf;background:#ff5c6d12}`;document.head.appendChild(css);
  const msg=(text,error=false)=>{const el=document.getElementById('authMessage');el.textContent=text;el.className='auth-message show'+(error?' error':'')};
  const busy=(btn,on,text)=>{btn.disabled=on;if(on){btn.dataset.old=btn.textContent;btn.textContent='Conectando...'}else btn.textContent=btn.dataset.old||text};
  async function oauth(provider,btn){if(!conexaoDisponivel){msg('A conexão com o Supabase ainda não está disponível.');return}busy(btn,true);try{const {error}=await client.auth.signInWithOAuth({provider,options:{redirectTo:window.location.href}});if(error)throw error}catch(e){msg('Não foi possível iniciar este login. Verifique se o provedor está ativado no Supabase.',true);busy(btn,false,provider==='google'?'🔵 Continuar com Google':'🔵 Continuar com Facebook')}}
  document.getElementById('authGoogle').onclick=e=>oauth('google',e.currentTarget);document.getElementById('authFacebook').onclick=e=>oauth('facebook',e.currentTarget);
  document.getElementById('authEmailForm').onsubmit=async e=>{e.preventDefault();if(!conexaoDisponivel){msg('A conexão com o Supabase ainda não está disponível.');return}const btn=e.target.querySelector('button');const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;busy(btn,true);try{const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;msg('Login realizado. Carregando seu painel...');if(data.session)showDashboard(data.session.user)}catch(err){msg('E-mail ou senha não reconhecidos. Você pode criar uma conta.',true);busy(btn,false,'Entrar com e-mail')}};
  document.getElementById('authCreate').onclick=async()=>{if(!conexaoDisponivel){msg('A conexão com o Supabase ainda não está disponível.');return}const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;if(!email||!password)return msg('Preencha e-mail e senha para criar a conta.',true);const b=document.getElementById('authCreate');busy(b,true);try{const {data,error}=await client.auth.signUp({email,password});if(error)throw error;msg(data.session?'Conta criada e login realizado.':'Conta criada. Confira o e-mail para confirmar o acesso.')}catch(err){msg('Não foi possível criar a conta. Confira o e-mail e a senha.',true)}busy(b,false,'Criar conta')};
  document.getElementById('authForgot').onclick=async()=>{if(!conexaoDisponivel){msg('A conexão com o Supabase ainda não está disponível.');return}const email=document.getElementById('authEmail').value.trim();if(!email)return msg('Digite seu e-mail primeiro para receber a recuperação.',true);try{const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:window.location.href});if(error)throw error;msg('Se este e-mail estiver cadastrado, você receberá as instruções de recuperação.')}catch(err){msg('Não foi possível iniciar a recuperação agora.',true)}};
  function showDashboard(user){login.style.display='none';dashboard.classList.add('show');window.scrollTo(0,0);const name=user.user_metadata?.full_name||user.user_metadata?.name||'Afiliado';const email=user.email||'';const h=dashboard.querySelector('.dash-head h1'),p=dashboard.querySelector('.profile b'),small=dashboard.querySelector('.profile small');if(h)h.textContent=`Olá, ${name} 👋`;if(p)p.textContent='Seu perfil de afiliado';if(small)small.textContent=email}
  if(conexaoDisponivel){client.auth.getSession().then(({data})=>{if(data.session)showDashboard(data.session.user)});client.auth.onAuthStateChange((event,session)=>{if(session&&(event==='SIGNED_IN'||event==='INITIAL_SESSION'))showDashboard(session)})}
  window.sair=async()=>{if(conexaoDisponivel)await client.auth.signOut();dashboard.classList.remove('show');login.style.display='grid';msg('Você saiu da sua conta.')};
})();
