(() => {
  if (document.getElementById('configurar-grupo-aura')) return;
  const css = document.createElement('style');
  css.textContent = `
    .configurar-cta{border:1px solid #55d7ff66!important;background:linear-gradient(110deg,#39c6ff18,#9b6cff18)!important;box-shadow:0 0 24px #39c6ff22!important}
    .configurar-backdrop{position:fixed;inset:0;z-index:100000;display:none;place-items:center;padding:18px;background:#02030acc;backdrop-filter:blur(10px)}.configurar-backdrop.open{display:grid}
    .configurar-modal{position:relative;width:min(520px,100%);max-height:92vh;overflow:auto;padding:28px;border:1px solid #a98bff66;border-radius:24px;background:linear-gradient(145deg,#17182a,#0a0c15);box-shadow:0 30px 100px #000d,0 0 50px #7042ff33}.configurar-close{position:absolute;right:15px;top:10px;border:0;background:none;color:#989bad;font-size:26px;cursor:pointer}.configurar-kicker{color:#65d9ff;font-size:10px;font-weight:bold;letter-spacing:2px}.configurar-modal h2{margin:9px 0;font-size:30px;letter-spacing:-1px}.configurar-modal .configurar-intro{color:#9799aa;font-size:12px}.configurar-progress{display:flex;gap:6px;margin:20px 0}.configurar-progress i{height:4px;flex:1;border-radius:5px;background:#ffffff16}.configurar-progress i.active{background:linear-gradient(90deg,#9364ff,#39c6ff)}.configurar-step h3{margin-bottom:14px;font-size:17px}.configurar-options{display:grid;gap:9px}.configurar-option{display:flex;align-items:center;gap:10px;width:100%;padding:13px;border:1px solid #ffffff15;border-radius:12px;color:#d7d5e4;background:#ffffff08;text-align:left;font-size:12px;cursor:pointer}.configurar-option:hover,.configurar-option.selected{border-color:#a98bff;background:#9b6cff1b}.configurar-option span{font-size:21px}.configurar-next{width:100%;margin-top:18px;padding:13px;border:0;border-radius:11px;color:#fff;background:linear-gradient(110deg,#9364ff,#39aee9);font-weight:bold;cursor:pointer}.configurar-next:disabled{opacity:.45;cursor:not-allowed}.configurar-result{display:none}.configurar-result.show{display:block}.configurar-score{display:flex;align-items:center;gap:17px;margin:18px 0;padding:17px;border:1px solid #55e6a555;border-radius:15px;background:#55e6a510}.configurar-score strong{color:#6ff0b1;font-size:39px;line-height:1}.configurar-score small{color:#9295a7;font-size:11px}.configurar-result ul{display:grid;gap:8px;margin:15px 0;padding:0;list-style:none;color:#c2c2ce;font-size:12px}.configurar-result li:before{content:'✓';margin-right:8px;color:#6ff0b1;font-weight:bold}.configurar-note{margin-top:15px;color:#777b90;font-size:10px}.configurar-restart{margin-top:12px;padding:10px 13px;border:1px solid #ffffff20;border-radius:10px;color:#fff;background:#ffffff0b;cursor:pointer}
  `;
  document.head.appendChild(css);

  const modal = document.createElement('div');
  modal.id='configurar-grupo-aura'; modal.className='configurar-backdrop';
  modal.innerHTML=`<div class="configurar-modal" role="dialog" aria-modal="true"><button class="configurar-close" aria-label="Fechar">×</button><div class="configurar-kicker">AURABOT COPILOT • DEMONSTRAÇÃO</div><h2>Configurar meu grupo ⚡</h2><p class="configurar-intro">Responda 3 perguntas e descubra a configuração ideal para o seu grupo.</p><div class="configurar-progress"><i class="active"></i><i></i><i></i></div><div class="configurar-step" data-step="1"><h3>Que tipo de grupo você administra?</h3><div class="configurar-options"><button class="configurar-option" data-value="amigos"><span>👥</span>Amigos e família</button><button class="configurar-option" data-value="negocio"><span>💼</span>Negócio ou atendimento</button><button class="configurar-option" data-value="comunidade"><span>🌐</span>Comunidade grande</button></div></div><div class="configurar-step" data-step="2" hidden><h3>Quantas pessoas participam?</h3><div class="configurar-options"><button class="configurar-option" data-value="pequeno"><span>🌱</span>Até 50 pessoas</button><button class="configurar-option" data-value="medio"><span>🚀</span>De 51 a 300 pessoas</button><button class="configurar-option" data-value="grande"><span>🔥</span>Mais de 300 pessoas</button></div></div><div class="configurar-step" data-step="3" hidden><h3>O que é mais importante para você?</h3><div class="configurar-options"><button class="configurar-option" data-value="protecao"><span>🛡️</span>Proteção e segurança</button><button class="configurar-option" data-value="gestao"><span>⚙️</span>Organização e gestão</button><button class="configurar-option" data-value="diversao"><span>🎮</span>Diversão e interação</button></div></div><button class="configurar-next" disabled>Continuar</button><div class="configurar-result"><div class="configurar-score"><strong class="score-number">0</strong><div><b>AuraBot Score recomendado</b><br><small>Configuração inicial sugerida</small></div></div><h3>Seu checklist inicial</h3><ul class="configurar-checklist"></ul><p class="configurar-note">Demonstração visual: ainda não altera um grupo real. Para ativar, fale com o suporte.</p><a class="configurar-next configurar-whatsapp" href="https://wa.me/5594984288511?text=Ol%C3%A1!%20Quero%20configurar%20meu%20grupo%20com%20a%20AuraBot." target="_blank">Falar com o suporte →</a><button class="configurar-restart">Refazer configuração</button></div></div>`;
  document.body.appendChild(modal);

  const abrir = () => modal.classList.add('open'); const fechar = () => modal.classList.remove('open');
  let botao = document.querySelector('.configurar-cta');
  if(!botao){botao=document.createElement('button');botao.className='button configurar-cta';botao.textContent='⚡ Configurar meu grupo';const alvo=document.querySelector('.buttons');if(alvo) alvo.appendChild(botao);else document.body.appendChild(botao)}
  botao.onclick=abrir; modal.querySelector('.configurar-close').onclick=fechar; modal.addEventListener('click',e=>{if(e.target===modal)fechar()});

  let etapa=1, respostas={}; const progresso=[...modal.querySelectorAll('.configurar-progress i')]; const continuar=modal.querySelector('.configurar-next');
  const atualizar=()=>{modal.querySelectorAll('.configurar-step').forEach(x=>x.hidden=Number(x.dataset.step)!==etapa);progresso.forEach((x,i)=>x.classList.toggle('active',i<etapa));continuar.disabled=!respostas[etapa];continuar.style.display=etapa===3?'block':'block';};
  modal.querySelectorAll('.configurar-step').forEach(step=>step.querySelectorAll('.configurar-option').forEach(op=>op.onclick=()=>{step.querySelectorAll('.configurar-option').forEach(x=>x.classList.remove('selected'));op.classList.add('selected');respostas[step.dataset.step]=op.dataset.value;atualizar()}));
  const mostrarResultado=()=>{const foco=respostas[3],tam=respostas[2],tipo=respostas[1];let score=78;if(tam==='grande')score+=10;if(tipo==='comunidade')score+=6;if(foco==='protecao')score+=5;score=Math.min(score,99);modal.querySelector('.score-number').textContent=score;const itens=foco==='protecao'?['Ativar proteção contra spam e links suspeitos','Criar sistema de advertências','Configurar cargos de administradores','Revisar permissões do grupo']:foco==='gestao'?['Organizar comandos favoritos','Ativar boas-vindas personalizadas','Criar mensagens fixadas','Configurar agenda de avisos']:['Ativar ranking de membros','Criar missões e recompensas','Liberar mini-jogos','Definir regras de convivência'];modal.querySelector('.configurar-checklist').innerHTML=itens.map(x=>`<li>${x}</li>`).join('');modal.querySelectorAll('.configurar-step,.configurar-progress,.configurar-modal>.configurar-next').forEach(x=>x.style.display='none');modal.querySelector('.configurar-result').classList.add('show');};
  continuar.onclick=()=>{if(etapa<3){etapa++;atualizar()}else mostrarResultado()};
  modal.querySelector('.configurar-restart').onclick=()=>{etapa=1;respostas={};modal.querySelector('.configurar-result').classList.remove('show');modal.querySelectorAll('.configurar-option').forEach(x=>x.classList.remove('selected'));modal.querySelectorAll('.configurar-step,.configurar-progress,.configurar-modal>.configurar-next').forEach(x=>x.style.display='');atualizar()};
  atualizar();
})();
